[package]
name = "submodules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magoo = "0.2.2"
submod = "0.1.2"
